function valuesInhomDBCModified = ...
    inputInletVelocityParabolic(fldMsh, inhomDBC, valuesInhomDBC, Umax)
    
    % Find inlet
    rowIndices = findInletNodeIndices(fldMsh, inhomDBC);
    rowIndices = inhomDBC( rowIndices );
    rowIndices = floor(rowIndices/3) + mod(rowIndices,3);
    % Sort 
    [sortedCoordinates, rowIndices] = sort(                             ...
        fldMsh.nodes(rowIndices,2),                         ...
        'ascend'                                                        ...
        );
    % Get parabolic distribution
    H = sortedCoordinates(end)-sortedCoordinates(1);
    values = parabolicInlet(                                            ...
        sortedCoordinates-sortedCoordinates(1),                         ...
        H,                                                              ...
        Umax                                                           ...
        );
    
    % Insert
    valuesInhomDBCModified = valuesInhomDBC;
    valuesInhomDBCModified(rowIndices) = values;
   

    % ---------------------------------------------------------------------
    function indices = findInletNodeIndices(fldMsh, inhomDBC)
        rows = floor(inhomDBC/3) + mod(inhomDBC,3 );
        indices = find(                                                 ... 
            abs(    fldMsh.nodes( rows ,1)                  ...
                    -                                                   ...
                    min(fldMsh.nodes(:,1)))                 ...
            <                                                           ...
            1e-10                                                       ...
            );
    end
    
    function value = parabolicInlet(y,H,Umax)
        value = 4*Umax*y.*(H-y)/H/H;
    end
    
end