function [] = input_inletVelocityParabolic( paramStruct, input )
    % [] = input_inletVelocityParabolic( paramStruct, input )
    % Changes the valuesInhomDBC field of the paramStruct
    
    % Find inlet
    rowIndices = findInletNodeIndices(paramStruct);
    rowIndices = paramStruct.inhomDBC( rowIndices );
    rowIndices = floor(rowIndices/3) + mod(rowIndices,3);
    % Sort 
    [sortedCoordinates, rowIndices] = sort(                             ...
        paramStruct.fldMsh.nodes(rowIndices,2),                         ...
        'ascend'                                                        ...
        );
    % Get parabolic distribution
    H = sortedCoordinates(end)-sortedCoordinates(1);
    values = parabolicInlet(                                            ...
        sortedCoordinates-sortedCoordinates(1),                         ...
        H,                                                              ...
        input                                                           ...
        );
    
    % Insert
    valuesInhomDBCModified = paramStruct.valuesInhomDBC;
    valuesInhomDBCModified(rowIndices) = values;
    paramStruct.setField(                                               ...
        {'valuesInhomDBC'},                                             ...
        {valuesInhomDBCModified}                                        ...
        );

    % ---------------------------------------------------------------------
    function indices = findInletNodeIndices(paramStruct)
        rows = floor(paramStruct.inhomDBC/3) + mod( paramStruct.inhomDBC,3 );
        indices = find(                                                 ... 
            abs(    paramStruct.fldMsh.nodes( rows ,1)                  ...
                    -                                                   ...
                    min(paramStruct.fldMsh.nodes(:,1)))                 ...
            <                                                           ...
            1e-10                                                       ...
            );
    end

    function value = parabolicInlet(y,H,Umax)
        value = 4*Umax*y.*(H-y)/H/H;
    end
    
end