function A = triangleArea (points)
    % area = triangleArea(points)
    % Returns the area of the input triangle defined by 'points'

    ydiff = -diff( [points(:,2);points(1,2)] );
    A =                                                             ...
        abs(                                                        ...
            (                                                       ...
                points(1,1)*ydiff(2)                                ...
                + points(2,1)*ydiff(3)                              ...
                + points(3,1)*ydiff(1)                              ...
             )                                                      ...
            / 2                                                     ...
        );
    
end